/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package police.gui;

import police.Session;

/**
 *
 * @author HP
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ProfileBtn = new javax.swing.JButton();
        FIRBtn = new javax.swing.JButton();
        CASEBtn = new javax.swing.JButton();
        CRIMINALBtn = new javax.swing.JButton();
        ANALYTICSBtn = new javax.swing.JButton();
        LOGOUTBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProfileBtn.setText("MANAGE OFFICERS");
        ProfileBtn.setBackground(new java.awt.Color(0, 0, 0));
        ProfileBtn.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        ProfileBtn.setForeground(new java.awt.Color(255, 255, 255));
        ProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileBtnActionPerformed(evt);
            }
        });
        jPanel2.add(ProfileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 25, 168, 41));

        FIRBtn.setBackground(new java.awt.Color(0, 0, 0));
        FIRBtn.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        FIRBtn.setForeground(new java.awt.Color(255, 255, 255));
        FIRBtn.setText("FIR MANAGEMENT");
        FIRBtn.setMaximumSize(new java.awt.Dimension(74, 23));
        FIRBtn.setMinimumSize(new java.awt.Dimension(74, 23));
        FIRBtn.setPreferredSize(new java.awt.Dimension(74, 23));
        FIRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIRBtnActionPerformed(evt);
            }
        });
        jPanel2.add(FIRBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 96, 168, 46));

        CASEBtn.setBackground(new java.awt.Color(0, 0, 0));
        CASEBtn.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        CASEBtn.setForeground(new java.awt.Color(255, 255, 255));
        CASEBtn.setText("CASE MANAGEMENT");
        CASEBtn.setMaximumSize(new java.awt.Dimension(74, 23));
        CASEBtn.setMinimumSize(new java.awt.Dimension(74, 23));
        CASEBtn.setPreferredSize(new java.awt.Dimension(74, 23));
        CASEBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CASEBtnActionPerformed(evt);
            }
        });
        jPanel2.add(CASEBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 173, 168, 46));

        CRIMINALBtn.setBackground(new java.awt.Color(0, 0, 0));
        CRIMINALBtn.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        CRIMINALBtn.setForeground(new java.awt.Color(255, 255, 255));
        CRIMINALBtn.setText("CRIMINAL DATABASE");
        CRIMINALBtn.setMaximumSize(new java.awt.Dimension(74, 23));
        CRIMINALBtn.setMinimumSize(new java.awt.Dimension(74, 23));
        CRIMINALBtn.setPreferredSize(new java.awt.Dimension(74, 23));
        CRIMINALBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CRIMINALBtnActionPerformed(evt);
            }
        });
        jPanel2.add(CRIMINALBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 254, 168, 46));

        ANALYTICSBtn.setBackground(new java.awt.Color(0, 0, 0));
        ANALYTICSBtn.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        ANALYTICSBtn.setForeground(new java.awt.Color(255, 255, 255));
        ANALYTICSBtn.setText("ANALYTICS & REPORTS");
        ANALYTICSBtn.setMaximumSize(new java.awt.Dimension(74, 23));
        ANALYTICSBtn.setMinimumSize(new java.awt.Dimension(74, 23));
        ANALYTICSBtn.setPreferredSize(new java.awt.Dimension(74, 23));
        ANALYTICSBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANALYTICSBtnActionPerformed(evt);
            }
        });
        jPanel2.add(ANALYTICSBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 342, 168, 46));

        LOGOUTBtn.setBackground(new java.awt.Color(204, 0, 0));
        LOGOUTBtn.setFont(new java.awt.Font("Segoe UI", 3, 11)); // NOI18N
        LOGOUTBtn.setForeground(new java.awt.Color(255, 255, 255));
        LOGOUTBtn.setText("LOGOUT");
        LOGOUTBtn.setMaximumSize(new java.awt.Dimension(74, 23));
        LOGOUTBtn.setMinimumSize(new java.awt.Dimension(74, 23));
        LOGOUTBtn.setPreferredSize(new java.awt.Dimension(74, 23));
        LOGOUTBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTBtnActionPerformed(evt);
            }
        });
        jPanel2.add(LOGOUTBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 418, 168, 46));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 180, 500));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMIN DASHBOARD");
        jLabel1.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 43, 430, 70));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileBtnActionPerformed
        new ManageOfficersForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ProfileBtnActionPerformed

    private void FIRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIRBtnActionPerformed
        new FIRForm("Admin").setVisible(true);
    }//GEN-LAST:event_FIRBtnActionPerformed

    private void CASEBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CASEBtnActionPerformed
        new CaseInvestigationDashboard("Admin").setVisible(true);
    }//GEN-LAST:event_CASEBtnActionPerformed

    private void CRIMINALBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CRIMINALBtnActionPerformed
        new CriminalForm("Admin").setVisible(true);
    }//GEN-LAST:event_CRIMINALBtnActionPerformed

    private void ANALYTICSBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANALYTICSBtnActionPerformed
            new AnalyticsDashboard().setVisible(true);
    }//GEN-LAST:event_ANALYTICSBtnActionPerformed

    private void LOGOUTBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTBtnActionPerformed
        Session.clearSession();
        new HomePageForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LOGOUTBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ANALYTICSBtn;
    private javax.swing.JButton CASEBtn;
    private javax.swing.JButton CRIMINALBtn;
    private javax.swing.JButton FIRBtn;
    private javax.swing.JButton LOGOUTBtn;
    private javax.swing.JButton ProfileBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
