/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package police.gui;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.*;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import police.*;
import police.model.*;

/**
 *
 * @author HP
 */
public class CompletedCasesForm extends javax.swing.JFrame 
{

    /**
     * Creates new form CompletedCasesForm
     */
    private JButton backButton;
    private JLabel caseLabel;
    private CSVHandler csvHandler;
    private DefaultTableModel tableModel;
    private String loggedInUsername;

    public CompletedCasesForm(String loggedInUsername) 
    {
        Casestable = new JTable(); 
        try 
        {
            csvHandler = new CSVHandler();
        }
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this, "Failed to initialize CSVHandler: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            return;
        }
        initComponents();
        tableModel = new DefaultTableModel();
        configureTable();
        populateTable();
        this.loggedInUsername = loggedInUsername;
        setLocationRelativeTo(null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        headinglbl = new javax.swing.JLabel();
        tableScrollPane = new javax.swing.JScrollPane();
        Casestable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        Backbtn = new javax.swing.JButton();
        ViewDetailsbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Completed Cases");
        setLocation(new java.awt.Point(0, 0));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        mainPanel.setPreferredSize(new java.awt.Dimension(600, 520));

        headinglbl.setBackground(new java.awt.Color(51, 102, 255));
        headinglbl.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        headinglbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headinglbl.setText("COMPLETED CASES");

        Casestable.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][] {},
            new String[] {"Investigation ID", "FIR ID", "Case Started", "Status", "View Details"}
        ));
        tableScrollPane.setViewportView(Casestable);

        Backbtn.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });

        ViewDetailsbtn.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        ViewDetailsbtn.setText("View Details");
        ViewDetailsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDetailsbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(ViewDetailsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(Backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Backbtn)
                    .addComponent(ViewDetailsbtn))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(headinglbl, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(headinglbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        new CaseInvestigationDashboard(loggedInUsername).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackbtnActionPerformed

    private void ViewDetailsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDetailsbtnActionPerformed
            int selectedRow = Casestable.getSelectedRow();
            if (selectedRow >= 0) {
                String investigationId = (String) Casestable.getValueAt(selectedRow, 0);
                Investigation investigation = csvHandler.findInvestigationById(investigationId);
                if (investigation != null)
                {
                    new DisplayCaseDetails(investigation,loggedInUsername).setVisible(true);
                    dispose();
                }
            } 
            else 
            {
                JOptionPane.showMessageDialog(this, "Please select a case.", "No Case Selected", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_ViewDetailsbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void configureTable() {
        Casestable.setRowHeight(25);
        Casestable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tableModel.setColumnIdentifiers(new String[]{"Investigation ID", "FIR ID", "Case Started", "Status"});
        Casestable.setModel(tableModel);
        Casestable.getColumnModel().getColumn(0).setPreferredWidth(120);
        Casestable.getColumnModel().getColumn(1).setPreferredWidth(100);
        Casestable.getColumnModel().getColumn(2).setPreferredWidth(100);
        Casestable.getColumnModel().getColumn(3).setPreferredWidth(100);
    }

    private void populateTable() {
        List<Investigation> investigations = csvHandler.loadInvestigations();
        System.out.println("Loaded " + investigations.size() + " investigations.");
        if (investigations.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No investigations found in CSV.", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
        List<Object[]> data = new java.util.ArrayList<>();
        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
        for (Investigation inv : investigations) {
            System.out.println("Investigation ID: " + inv.getInvestigationId() + ", Status: " + inv.getStatus());
            if (inv.getStatus() != null && inv.getStatus().equalsIgnoreCase("Completed")) {
                data.add(new Object[]{
                    inv.getInvestigationId(),
                    inv.getFirId(),
                    sdf.format(inv.getCreationDate()),
                    inv.getStatus()
                });
                System.out.println("Added row for INV: " + inv.getInvestigationId());
            }
        }
        tableModel.setDataVector(data.toArray(new Object[0][]), new String[]{"Investigation ID", "FIR ID", "Case Started", "Status"});
        System.out.println("Rows after setDataVector: " + tableModel.getRowCount());
        if (tableModel.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No completed cases found.", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
        Casestable.repaint();
    }
    
    public void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompletedCasesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompletedCasesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompletedCasesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompletedCasesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run()
            {
                new CompletedCasesForm(loggedInUsername).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JTable Casestable;
    private javax.swing.JButton ViewDetailsbtn;
    private javax.swing.JLabel headinglbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane tableScrollPane;
    // End of variables declaration//GEN-END:variables
}
