/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package police.gui;
import police.model.Complaint;
import javax.swing.*;
import java.awt.*;
import java.io.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;
import police.CSVHandler;
import police.gui.CheckComplaintsForm;

/**
 *
 * @author HP
 */
public class DetailedViewComplainForm extends javax.swing.JFrame {

    /**
     * Creates new form DetailedViewComplainForm
     */
    private static String loggedInUsername;
    private Complaint complaint;
    private String evidencePath;
//    public DetailedViewComplainForm(Complaint complaint, String loggedInUsername) 
//    {
//        initComponents();
//        setLocationRelativeTo(null);
//        populateFields(); 
//        this.loggedInUsername = loggedInUsername;
//    }
    
    public DetailedViewComplainForm(Complaint complaint, String loggedInUsername) 
    {
        if (complaint == null || complaint.getComplaintId() == null || complaint.getComplaintId().isEmpty()) {
            System.err.println("Error: Invalid complaint provided to DetailedViewComplainForm, complaint: " + complaint);
            JOptionPane.showMessageDialog(null, "Invalid complaint data.", "Error", JOptionPane.ERROR_MESSAGE);
            dispose();
            return;
        }
        this.complaint = complaint;
        this.loggedInUsername = loggedInUsername;
        System.out.println("Constructing DetailedViewComplainForm for complaint ID: " + complaint.getComplaintId());
        initComponents();
        setLocationRelativeTo(null);
        populateFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        IDlbl = new javax.swing.JLabel();
        Namelbl = new javax.swing.JLabel();
        Contactlbl = new javax.swing.JLabel();
        NIClbl = new javax.swing.JLabel();
        Datelbl = new javax.swing.JLabel();
        Timelbl = new javax.swing.JLabel();
        Locationlbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Descriptiontxt = new javax.swing.JTextArea();
        Statuslbl = new javax.swing.JLabel();
        Backbtn = new javax.swing.JButton();
        CheckEvidencebtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        Addresslbl = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        FatherNamelbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        headinglbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Complain Details");
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(0, 0, 102));
        mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        mainPanel.setPreferredSize(new java.awt.Dimension(630, 1000));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Complain ID :");
        mainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 100, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Complainant Name :");
        mainPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contact :");
        mainPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 70, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NIC :");
        mainPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Incident Date :");
        mainPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Incident Time :");
        mainPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Location :");
        mainPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Description :");
        mainPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Evidence :");
        mainPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Status :");
        mainPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 670, 80, -1));

        IDlbl.setForeground(new java.awt.Color(255, 255, 255));
        mainPanel.add(IDlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 440, 17));

        Namelbl.setForeground(new java.awt.Color(255, 255, 255));
        mainPanel.add(Namelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 430, 17));

        Contactlbl.setForeground(new java.awt.Color(255, 255, 255));
        mainPanel.add(Contactlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 430, 17));

        NIClbl.setForeground(new java.awt.Color(255, 255, 255));
        mainPanel.add(NIClbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 430, 17));

        Datelbl.setForeground(new java.awt.Color(255, 255, 255));
        mainPanel.add(Datelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 430, 17));

        Timelbl.setForeground(new java.awt.Color(255, 255, 255));
        mainPanel.add(Timelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 420, 17));

        Locationlbl.setForeground(new java.awt.Color(255, 255, 255));
        mainPanel.add(Locationlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 430, 430, 16));

        Descriptiontxt.setEditable(false);
        Descriptiontxt.setColumns(20);
        Descriptiontxt.setRows(5);
        jScrollPane1.setViewportView(Descriptiontxt);

        mainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 447, 98));

        Statuslbl.setForeground(new java.awt.Color(255, 255, 255));
        mainPanel.add(Statuslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 670, 234, 16));

        Backbtn.setBackground(new java.awt.Color(204, 0, 0));
        Backbtn.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        Backbtn.setForeground(new java.awt.Color(255, 255, 255));
        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });
        mainPanel.add(Backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 720, 92, 33));

        CheckEvidencebtn.setBackground(new java.awt.Color(0, 0, 0));
        CheckEvidencebtn.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        CheckEvidencebtn.setForeground(new java.awt.Color(255, 255, 255));
        CheckEvidencebtn.setText("Check Evidence");
        CheckEvidencebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckEvidencebtnActionPerformed(evt);
            }
        });
        mainPanel.add(CheckEvidencebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 610, 160, 23));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Address :");
        mainPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        Addresslbl.setForeground(new java.awt.Color(255, 255, 255));
        mainPanel.add(Addresslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 430, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Father's Name :");
        mainPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 110, -1));

        FatherNamelbl.setForeground(new java.awt.Color(255, 255, 255));
        mainPanel.add(FatherNamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 430, 17));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        headinglbl.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        headinglbl.setForeground(new java.awt.Color(255, 255, 0));
        headinglbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headinglbl.setText("View Complaints");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addComponent(headinglbl, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(headinglbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 70));

        jScrollPane2.setViewportView(mainPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_BackbtnActionPerformed

    private void CheckEvidencebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckEvidencebtnActionPerformed
        if (evidencePath != null && !evidencePath.trim().isEmpty()) {
            try {
                File file = new File(evidencePath);
                if (file.exists())
                {
                    Desktop.getDesktop().open(file);
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Evidence file not found: " + evidencePath, "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            catch (IOException e)
            {
                JOptionPane.showMessageDialog(this, "Failed to open evidence: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
            catch (UnsupportedOperationException e)
            {
                JOptionPane.showMessageDialog(this, "Opening files is not supported on this system.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No evidence provided.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CheckEvidencebtnActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailedViewComplainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailedViewComplainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailedViewComplainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailedViewComplainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailedViewComplainForm(complaint,loggedInUsername).setVisible(true);
            }
        });
    }
    
    private void populateFields() 
    {
        if (complaint == null) 
        {
            System.err.println("Error: Complaint is null in populateFields");
            JOptionPane.showMessageDialog(this, "Invalid complaint data.", "Error", JOptionPane.ERROR_MESSAGE);
            dispose();
            return;
        }
        try 
        {
            System.out.println("Populating fields for complaint ID: " + complaint.getComplaintId());
            System.out.println("Complaint details: " +
                "ID=" + complaint.getComplaintId() + ", " +
                "Name=" + complaint.getComplainantName() + ", " +
                "FatherName=" + complaint.getComplainantFatherName() + ", " +
                "Contact=" + complaint.getContact() + ", " +
                "NIC=" + complaint.getNicNumber() + ", " +
                "Address=" + complaint.getAddress() + ", " +
                "IncidentDate=" + complaint.getIncidentDate() + ", " +
                "IncidentTime=" + complaint.getIncidentTime() + ", " +
                "Location=" + complaint.getLocation() + ", " +
                "Description=" + complaint.getDescription() + ", " +
                "EvidencePath=" + complaint.getEvidencePath() + ", " +
                "Status=" + complaint.getStatus());

            IDlbl.setText(complaint.getComplaintId() != null ? complaint.getComplaintId() : "N/A");
            Namelbl.setText(complaint.getComplainantName() != null ? complaint.getComplainantName() : "N/A");
            FatherNamelbl.setText(complaint.getComplainantFatherName() != null ? complaint.getComplainantFatherName() : "N/A");
            Contactlbl.setText(complaint.getContact() != null ? complaint.getContact() : "N/A");
            NIClbl.setText(complaint.getNicNumber() != null ? complaint.getNicNumber() : "N/A");
            Addresslbl.setText(complaint.getAddress() != null ? complaint.getAddress() : "N/A");
            Datelbl.setText(complaint.getIncidentDate() != null ? complaint.getIncidentDate() : "N/A");
            Timelbl.setText(complaint.getIncidentTime() != null ? complaint.getIncidentTime() : "N/A");
            Locationlbl.setText(complaint.getLocation() != null ? complaint.getLocation() : "N/A");
            Descriptiontxt.setText(complaint.getDescription() != null ? complaint.getDescription() : "N/A");
            evidencePath = complaint.getEvidencePath();
            CheckEvidencebtn.setText(complaint.getEvidencePath() != null && !complaint.getEvidencePath().isEmpty() ? "View Evidence" : "No Evidence");
            Statuslbl.setText(complaint.getStatus() != null ? complaint.getStatus() : "N/A");
            System.out.println("Successfully populated complaint details: " + complaint.getComplaintId());
        } 
        catch (Exception e) 
        {
            System.err.println("Error populating complaint details: " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error displaying complaint: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            dispose();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Addresslbl;
    private javax.swing.JButton Backbtn;
    private javax.swing.JButton CheckEvidencebtn;
    private javax.swing.JLabel Contactlbl;
    private javax.swing.JLabel Datelbl;
    private javax.swing.JTextArea Descriptiontxt;
    private javax.swing.JLabel FatherNamelbl;
    private javax.swing.JLabel IDlbl;
    private javax.swing.JLabel Locationlbl;
    private javax.swing.JLabel NIClbl;
    private javax.swing.JLabel Namelbl;
    private javax.swing.JLabel Statuslbl;
    private javax.swing.JLabel Timelbl;
    private javax.swing.JLabel headinglbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
