/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package police.gui;
import police.*;
import police.model.*;
import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.text.SimpleDateFormat;
/**
 *
 * @author HP
 */
public class DisplayCaseDetails extends javax.swing.JFrame 
{

    /**
     * Creates new form DisplayCaseDetails
     */
    private static String loggedInUsername;
    private Investigation investigation;
    private CSVHandler csvHandler;
    public DisplayCaseDetails(Investigation investigation,String loggedInUsername)
    {
        this.investigation = investigation;
        this.csvHandler = new CSVHandler();
        initComponents();
        setLocationRelativeTo(null);
        loadInvestigation();
        this.loggedInUsername = loggedInUsername;
        setLocationRelativeTo(null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();
        headinglbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        investigationIdField = new javax.swing.JTextField();
        firIdField = new javax.swing.JTextField();
        leadOfficerIdField = new javax.swing.JTextField();
        assisstantOfficerIdField = new javax.swing.JTextField();
        caseStartedField = new javax.swing.JTextField();
        closingDateField = new javax.swing.JTextField();
        incidentDateField = new javax.swing.JTextField();
        incidentTimeField = new javax.swing.JTextField();
        locationField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        otherDetailsTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        witnessTextArea = new javax.swing.JTextArea();
        crimeTypeField = new javax.swing.JTextField();
        suspectsField = new javax.swing.JTextField();
        viewEvidenceButton = new javax.swing.JButton();
        caseResultField = new javax.swing.JTextField();
        finalCriminalField = new javax.swing.JTextField();
        statusComboBox = new javax.swing.JComboBox<>();
        complainantNameField = new javax.swing.JTextField();
        complainantFatherNameField = new javax.swing.JTextField();
        contactField = new javax.swing.JTextField();
        nicNoField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        Backbtn01 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Case Details");

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        mainPanel.setPreferredSize(new java.awt.Dimension(680, 1000));
        mainPanel.setVerifyInputWhenFocusTarget(false);

        headinglbl.setBackground(new java.awt.Color(51, 102, 255));
        headinglbl.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        headinglbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headinglbl.setText("INVESTIGATION  DETAILS");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Investigation ID :");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("FIR ID :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Lead Officer ID :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Second Officer ID :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Case Started :");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Case Ended :");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Incident Date :");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Incident Time :");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Incident Location :");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Description :");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Crime Type :");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Suspects :");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Witness Statements :");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Other Details :");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("Case Result :");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Final Criminal :");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("Status :");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("Evidence :");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel19.setText("Complainant Name :");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel20.setText("Complainant Father Name :");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setText("Contact :");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setText("Address :");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setText("CNIC No :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(23, 23, 23))
        );

        investigationIdField.setEditable(false);
        investigationIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                investigationIdFieldActionPerformed(evt);
            }
        });

        firIdField.setEditable(false);
        firIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firIdFieldActionPerformed(evt);
            }
        });

        leadOfficerIdField.setEditable(false);
        leadOfficerIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leadOfficerIdFieldActionPerformed(evt);
            }
        });

        assisstantOfficerIdField.setEditable(false);
        assisstantOfficerIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assisstantOfficerIdFieldActionPerformed(evt);
            }
        });

        caseStartedField.setEditable(false);
        caseStartedField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caseStartedFieldActionPerformed(evt);
            }
        });

        closingDateField.setEditable(false);
        closingDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closingDateFieldActionPerformed(evt);
            }
        });

        incidentDateField.setEditable(false);
        incidentDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incidentDateFieldActionPerformed(evt);
            }
        });

        incidentTimeField.setEditable(false);
        incidentTimeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incidentTimeFieldActionPerformed(evt);
            }
        });

        locationField.setEditable(false);
        locationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationFieldActionPerformed(evt);
            }
        });

        descriptionTextArea.setEditable(false);
        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(descriptionTextArea);

        otherDetailsTextArea.setEditable(false);
        otherDetailsTextArea.setColumns(20);
        otherDetailsTextArea.setRows(5);
        jScrollPane2.setViewportView(otherDetailsTextArea);

        witnessTextArea.setEditable(false);
        witnessTextArea.setColumns(20);
        witnessTextArea.setRows(5);
        jScrollPane3.setViewportView(witnessTextArea);

        crimeTypeField.setEditable(false);
        crimeTypeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crimeTypeFieldActionPerformed(evt);
            }
        });

        suspectsField.setEditable(false);
        suspectsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suspectsFieldActionPerformed(evt);
            }
        });

        viewEvidenceButton.setText("View Evidence");
        viewEvidenceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEvidenceButtonActionPerformed(evt);
            }
        });

        caseResultField.setEditable(false);
        caseResultField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caseResultFieldActionPerformed(evt);
            }
        });

        finalCriminalField.setEditable(false);
        finalCriminalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalCriminalFieldActionPerformed(evt);
            }
        });

        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        complainantNameField.setEditable(false);
        complainantNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complainantNameFieldActionPerformed(evt);
            }
        });

        complainantFatherNameField.setEditable(false);
        complainantFatherNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complainantFatherNameFieldActionPerformed(evt);
            }
        });

        contactField.setEditable(false);
        contactField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactFieldActionPerformed(evt);
            }
        });

        nicNoField.setEditable(false);
        nicNoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicNoFieldActionPerformed(evt);
            }
        });

        addressField.setEditable(false);
        addressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(finalCriminalField, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(caseResultField, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(viewEvidenceButton)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                        .addComponent(suspectsField)
                        .addComponent(crimeTypeField)
                        .addComponent(jScrollPane1)
                        .addComponent(locationField)
                        .addComponent(incidentDateField)
                        .addComponent(closingDateField)
                        .addComponent(caseStartedField)
                        .addComponent(assisstantOfficerIdField)
                        .addComponent(leadOfficerIdField)
                        .addComponent(firIdField)
                        .addComponent(investigationIdField)
                        .addComponent(complainantNameField)
                        .addComponent(complainantFatherNameField)
                        .addComponent(contactField)
                        .addComponent(nicNoField)
                        .addComponent(addressField)
                        .addComponent(incidentTimeField)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(investigationIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(firIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(leadOfficerIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(assisstantOfficerIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(caseStartedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(closingDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(complainantNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(complainantFatherNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contactField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nicNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(incidentDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(incidentTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(locationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(crimeTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(suspectsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewEvidenceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(caseResultField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(finalCriminalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Backbtn01.setFont(new java.awt.Font("Bodoni MT", 1, 16)); // NOI18N
        Backbtn01.setText("Back");
        Backbtn01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Backbtn01ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Backbtn01, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(headinglbl)
                        .addGap(185, 185, 185))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(headinglbl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addComponent(Backbtn01, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane4.setViewportView(mainPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void investigationIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_investigationIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_investigationIdFieldActionPerformed

    private void firIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firIdFieldActionPerformed

    private void leadOfficerIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leadOfficerIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leadOfficerIdFieldActionPerformed

    private void assisstantOfficerIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assisstantOfficerIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assisstantOfficerIdFieldActionPerformed

    private void caseStartedFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caseStartedFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caseStartedFieldActionPerformed

    private void closingDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closingDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_closingDateFieldActionPerformed

    private void incidentDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incidentDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_incidentDateFieldActionPerformed

    private void incidentTimeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incidentTimeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_incidentTimeFieldActionPerformed

    private void locationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationFieldActionPerformed

    private void crimeTypeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crimeTypeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crimeTypeFieldActionPerformed

    private void suspectsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suspectsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suspectsFieldActionPerformed

    private void caseResultFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caseResultFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caseResultFieldActionPerformed

    private void finalCriminalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalCriminalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finalCriminalFieldActionPerformed

    private void viewEvidenceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEvidenceButtonActionPerformed
            if (investigation.getEvidencePaths().isEmpty()) 
            {
                JOptionPane.showMessageDialog(this, "No evidence available.", "Info", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            JList<String> evidenceList = new JList<>(investigation.getEvidencePaths().toArray(new String[0]));
            evidenceList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            JOptionPane.showMessageDialog(this, new JScrollPane(evidenceList), "Select Evidence to View", JOptionPane.PLAIN_MESSAGE);
            String selectedPath = evidenceList.getSelectedValue();
            if (selectedPath != null) 
            {
                try
                {
                    Desktop.getDesktop().open(new File(selectedPath));
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Error opening file: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
    }//GEN-LAST:event_viewEvidenceButtonActionPerformed

    private void Backbtn01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Backbtn01ActionPerformed
        new CompletedCasesForm(loggedInUsername).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Backbtn01ActionPerformed

    private void complainantNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complainantNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_complainantNameFieldActionPerformed

    private void complainantFatherNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complainantFatherNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_complainantFatherNameFieldActionPerformed

    private void contactFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactFieldActionPerformed

    private void nicNoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicNoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicNoFieldActionPerformed

    private void addressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayCaseDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayCaseDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayCaseDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayCaseDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayCaseDetails(investigation, loggedInUsername).setVisible(true);
            }
        });
    }
    
    private void loadInvestigation() 
    {
        investigationIdField.setText(investigation.getInvestigationId());
        firIdField.setText(investigation.getFirId());
        leadOfficerIdField.setText(investigation.getOfficerId1() != null ? investigation.getOfficerId1() : "");
        assisstantOfficerIdField.setText(investigation.getOfficerId2() != null ? investigation.getOfficerId2() : "");
        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
        caseStartedField.setText(sdf.format(investigation.getCreationDate()));
        closingDateField.setText(sdf.format(investigation.getLastUpdated()));
        suspectsField.setText(investigation.getSuspects());
        witnessTextArea.setText(investigation.getWitnessStatements());
        otherDetailsTextArea.setText(investigation.getOtherDetails());
        caseResultField.setText(investigation.getCaseResult());
        finalCriminalField.setText(investigation.getFinalCriminal());
        statusComboBox.setModel(new DefaultComboBoxModel<>(new String[]{"Initiated", "Active", "Completed"}));
        statusComboBox.setSelectedItem(investigation.getStatus());
        CSVHandler.FIRData firData = csvHandler.getFIRData(investigation.getFirId());
        if (firData != null) 
        {
            complainantNameField.setText(firData.getComplainantName());
            complainantFatherNameField.setText(firData.getFathersName());
            contactField.setText(firData.getContact());
            addressField.setText(firData.getAddress());
            nicNoField.setText(firData.getNicNumber());
            incidentDateField.setText(firData.getIncidentDate() != null ? sdf.format(firData.getIncidentDate()) : "");
            incidentTimeField.setText(firData.getIncidentTime());
            locationField.setText(firData.getLocation());
            descriptionTextArea.setText(firData.getDescription());
            crimeTypeField.setText(firData.getCrimeType());
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn01;
    private javax.swing.JTextField addressField;
    private javax.swing.JTextField assisstantOfficerIdField;
    private javax.swing.JTextField caseResultField;
    private javax.swing.JTextField caseStartedField;
    private javax.swing.JTextField closingDateField;
    private javax.swing.JTextField complainantFatherNameField;
    private javax.swing.JTextField complainantNameField;
    private javax.swing.JTextField contactField;
    private javax.swing.JTextField crimeTypeField;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JTextField finalCriminalField;
    private javax.swing.JTextField firIdField;
    private javax.swing.JLabel headinglbl;
    private javax.swing.JTextField incidentDateField;
    private javax.swing.JTextField incidentTimeField;
    private javax.swing.JTextField investigationIdField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField leadOfficerIdField;
    private javax.swing.JTextField locationField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField nicNoField;
    private javax.swing.JTextArea otherDetailsTextArea;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JTextField suspectsField;
    private javax.swing.JButton viewEvidenceButton;
    private javax.swing.JTextArea witnessTextArea;
    // End of variables declaration//GEN-END:variables
}
