/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package police.gui;
import police.*;
import police.model.*;
import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 *
 * @author HP
 */
public class InvestigationForm extends javax.swing.JFrame {

    /**
     * Creates new form InvestigationForm
     */
    private Investigation investigation;
    private CSVHandler csvHandler;
    private String loggedInUsername;
    private List<String> evidencePaths;
    private boolean changesMade = false;

    public InvestigationForm(Investigation investigation, String loggedInUsername) {
        this.investigation = investigation;
        setLocationRelativeTo(null);
        this.loggedInUsername = loggedInUsername;
        this.evidencePaths = new ArrayList<>(investigation.getEvidencePaths() != null ? investigation.getEvidencePaths() : new ArrayList<>());
        try 
        {
            csvHandler = new CSVHandler();
        }
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this, "Failed to initialize CSVHandler: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        initComponents();
        disablecombo();
        loadInvestigation();
        witnessTextArea.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void changedUpdate(javax.swing.event.DocumentEvent e) { changesMade = true; }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { changesMade = true; }
            public void insertUpdate(javax.swing.event.DocumentEvent e) { changesMade = true; }
        });
        otherDetailsTextArea.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void changedUpdate(javax.swing.event.DocumentEvent e) { changesMade = true; }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { changesMade = true; }
            public void insertUpdate(javax.swing.event.DocumentEvent e) { changesMade = true; }
        });
        suspectsField.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void changedUpdate(javax.swing.event.DocumentEvent e) { changesMade = true; }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { changesMade = true; }
            public void insertUpdate(javax.swing.event.DocumentEvent e) { changesMade = true; }
        });
        caseResultField.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void changedUpdate(javax.swing.event.DocumentEvent e) { changesMade = true; }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { changesMade = true; }
            public void insertUpdate(javax.swing.event.DocumentEvent e) { changesMade = true; }
        });
        finalCriminalField.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void changedUpdate(javax.swing.event.DocumentEvent e) { changesMade = true; }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { changesMade = true; }
            public void insertUpdate(javax.swing.event.DocumentEvent e) { changesMade = true; }
        });
        statusComboBox.addActionListener(e -> changesMade = true);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Savebtn1 = new javax.swing.JButton();
        jMenuItem1 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        jScrollPane4 = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();
        headinglbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        investigationIdField = new javax.swing.JTextField();
        firIdField = new javax.swing.JTextField();
        leadOfficerIdField = new javax.swing.JTextField();
        assisstantOfficerIdField = new javax.swing.JTextField();
        caseStartedField = new javax.swing.JTextField();
        closingDateField = new javax.swing.JTextField();
        incidentDateField = new javax.swing.JTextField();
        incidentTimeField = new javax.swing.JTextField();
        locationField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        otherDetailsTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        witnessTextArea = new javax.swing.JTextArea();
        crimeTypeField = new javax.swing.JTextField();
        suspectsField = new javax.swing.JTextField();
        viewEvidenceButton = new javax.swing.JButton();
        caseResultField = new javax.swing.JTextField();
        finalCriminalField = new javax.swing.JTextField();
        statusComboBox = new javax.swing.JComboBox<>();
        complainantNameField = new javax.swing.JTextField();
        complainantFatherNameField = new javax.swing.JTextField();
        contactField = new javax.swing.JTextField();
        nicNoField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        addEvidenceButton = new javax.swing.JButton();
        removeEvidenceButton = new javax.swing.JButton();
        Backbtn = new javax.swing.JButton();
        Savebtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        Savebtn1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        Savebtn1.setText("Save");

        jMenuItem1.setText("jMenuItem1");

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(720, 650));

        mainPanel.setBackground(new java.awt.Color(0, 0, 102));
        mainPanel.setForeground(new java.awt.Color(0, 0, 102));
        mainPanel.setPreferredSize(new java.awt.Dimension(700, 1200));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headinglbl.setBackground(new java.awt.Color(51, 102, 255));
        headinglbl.setFont(new java.awt.Font("Wide Latin", 0, 18)); // NOI18N
        headinglbl.setForeground(new java.awt.Color(255, 255, 0));
        headinglbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headinglbl.setText("CASE DETAILS / MANAGEMENT");
        mainPanel.add(headinglbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 18, 730, 41));

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Investigation ID :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FIR ID :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 55, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Lead Officer ID :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Second Officer ID :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 125, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Case Started :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Last Updated : ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 195, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Incident Date :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 405, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Incident Time :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Incident Location :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 475, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Description :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 510, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Crime Type :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 545, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Suspects :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Witness Statements :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 615, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Other Details :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 685, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Case Result :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 720, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Final Criminal :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 755, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Status :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 792, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Evidence :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 650, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Complainant Name :");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 230, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Complainant Father Name :");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 265, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Contact :");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 300, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Address :");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 335, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("CNIC No :");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 370, -1, -1));

        mainPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 77, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setForeground(new java.awt.Color(0, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        investigationIdField.setEditable(false);
        investigationIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                investigationIdFieldActionPerformed(evt);
            }
        });
        jPanel2.add(investigationIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 18, 321, -1));

        firIdField.setEditable(false);
        firIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firIdFieldActionPerformed(evt);
            }
        });
        jPanel2.add(firIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 52, 321, -1));

        leadOfficerIdField.setEditable(false);
        leadOfficerIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leadOfficerIdFieldActionPerformed(evt);
            }
        });
        jPanel2.add(leadOfficerIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 86, 321, -1));

        assisstantOfficerIdField.setEditable(false);
        assisstantOfficerIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assisstantOfficerIdFieldActionPerformed(evt);
            }
        });
        jPanel2.add(assisstantOfficerIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 120, 321, -1));

        caseStartedField.setEditable(false);
        caseStartedField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caseStartedFieldActionPerformed(evt);
            }
        });
        jPanel2.add(caseStartedField, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 160, 321, -1));

        closingDateField.setEditable(false);
        closingDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closingDateFieldActionPerformed(evt);
            }
        });
        jPanel2.add(closingDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 194, 321, -1));

        incidentDateField.setEditable(false);
        incidentDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incidentDateFieldActionPerformed(evt);
            }
        });
        jPanel2.add(incidentDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 403, 321, -1));

        incidentTimeField.setEditable(false);
        incidentTimeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incidentTimeFieldActionPerformed(evt);
            }
        });
        jPanel2.add(incidentTimeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 437, 321, -1));

        locationField.setEditable(false);
        locationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationFieldActionPerformed(evt);
            }
        });
        jPanel2.add(locationField, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 477, 321, -1));

        descriptionTextArea.setEditable(false);
        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(descriptionTextArea);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 511, 321, 26));

        otherDetailsTextArea.setColumns(20);
        otherDetailsTextArea.setRows(5);
        jScrollPane2.setViewportView(otherDetailsTextArea);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 690, 321, 26));

        witnessTextArea.setColumns(20);
        witnessTextArea.setRows(5);
        jScrollPane3.setViewportView(witnessTextArea);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 617, 321, 26));

        crimeTypeField.setEditable(false);
        crimeTypeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crimeTypeFieldActionPerformed(evt);
            }
        });
        jPanel2.add(crimeTypeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 549, 321, -1));

        suspectsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suspectsFieldActionPerformed(evt);
            }
        });
        jPanel2.add(suspectsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 583, 321, -1));

        viewEvidenceButton.setBackground(new java.awt.Color(0, 0, 0));
        viewEvidenceButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        viewEvidenceButton.setForeground(new java.awt.Color(255, 255, 255));
        viewEvidenceButton.setText("View Evidence");
        viewEvidenceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEvidenceButtonActionPerformed(evt);
            }
        });
        jPanel2.add(viewEvidenceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 655, -1, -1));

        caseResultField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caseResultFieldActionPerformed(evt);
            }
        });
        jPanel2.add(caseResultField, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 722, 321, -1));

        finalCriminalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalCriminalFieldActionPerformed(evt);
            }
        });
        jPanel2.add(finalCriminalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 756, 321, -1));

        statusComboBox.setEditable(true);
        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Completed" }));
        statusComboBox.setToolTipText("");
        statusComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusComboBoxActionPerformed(evt);
            }
        });
        jPanel2.add(statusComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 790, -1, -1));

        complainantNameField.setEditable(false);
        complainantNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complainantNameFieldActionPerformed(evt);
            }
        });
        jPanel2.add(complainantNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 228, 321, -1));

        complainantFatherNameField.setEditable(false);
        complainantFatherNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complainantFatherNameFieldActionPerformed(evt);
            }
        });
        jPanel2.add(complainantFatherNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 264, 321, -1));

        contactField.setEditable(false);
        contactField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactFieldActionPerformed(evt);
            }
        });
        jPanel2.add(contactField, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 301, 321, -1));

        nicNoField.setEditable(false);
        nicNoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicNoFieldActionPerformed(evt);
            }
        });
        jPanel2.add(nicNoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 369, 321, -1));

        addressField.setEditable(false);
        addressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressFieldActionPerformed(evt);
            }
        });
        jPanel2.add(addressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 335, 321, -1));

        addEvidenceButton.setBackground(new java.awt.Color(51, 204, 0));
        addEvidenceButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        addEvidenceButton.setForeground(new java.awt.Color(255, 255, 255));
        addEvidenceButton.setText("Add Evidence");
        addEvidenceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEvidenceButtonActionPerformed(evt);
            }
        });
        jPanel2.add(addEvidenceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 655, -1, -1));

        removeEvidenceButton.setBackground(new java.awt.Color(204, 0, 0));
        removeEvidenceButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        removeEvidenceButton.setForeground(new java.awt.Color(255, 255, 255));
        removeEvidenceButton.setText("Remove Evidence");
        removeEvidenceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEvidenceButtonActionPerformed(evt);
            }
        });
        jPanel2.add(removeEvidenceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 655, 130, -1));

        Backbtn.setBackground(new java.awt.Color(204, 0, 0));
        Backbtn.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        Backbtn.setForeground(new java.awt.Color(255, 255, 255));
        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });
        jPanel2.add(Backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 850, 100, -1));

        Savebtn.setBackground(new java.awt.Color(51, 204, 0));
        Savebtn.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        Savebtn.setForeground(new java.awt.Color(255, 255, 255));
        Savebtn.setText("Save");
        Savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavebtnActionPerformed(evt);
            }
        });
        jPanel2.add(Savebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 850, 80, -1));

        mainPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 77, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        mainPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, -1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        mainPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 70));

        jScrollPane4.setViewportView(mainPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavebtnActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to save the changes?", "Confirm Save", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION)
        {
            saveChanges();
        }
    }//GEN-LAST:event_SavebtnActionPerformed

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        if (changesMade)
        {
            int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to leave? All changes made will be lost.", "Confirm Leave", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (response == JOptionPane.YES_OPTION)
            {
                new OngoingCasesForm(loggedInUsername).setVisible(true);
                dispose();
            }
        }
        else
        {
            new OngoingCasesForm(loggedInUsername).setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_BackbtnActionPerformed

    private void removeEvidenceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEvidenceButtonActionPerformed
        deleteEvidence();
        changesMade = true;
    }//GEN-LAST:event_removeEvidenceButtonActionPerformed

    private void addEvidenceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEvidenceButtonActionPerformed
        addEvidence();
        changesMade = true;
    }//GEN-LAST:event_addEvidenceButtonActionPerformed

    private void addressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressFieldActionPerformed

    private void nicNoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicNoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicNoFieldActionPerformed

    private void contactFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactFieldActionPerformed

    private void complainantFatherNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complainantFatherNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_complainantFatherNameFieldActionPerformed

    private void complainantNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complainantNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_complainantNameFieldActionPerformed

    private void statusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusComboBoxActionPerformed

    private void finalCriminalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalCriminalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finalCriminalFieldActionPerformed

    private void caseResultFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caseResultFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caseResultFieldActionPerformed

    private void viewEvidenceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEvidenceButtonActionPerformed
        if (investigation.getEvidencePaths().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "No evidence available.", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        JList<String> evidenceList = new JList<>(investigation.getEvidencePaths().toArray(new String[0]));
        evidenceList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        JOptionPane.showMessageDialog(this, new JScrollPane(evidenceList), "Select Evidence to View", JOptionPane.PLAIN_MESSAGE);
        String selectedPath = evidenceList.getSelectedValue();
        if (selectedPath != null)
        {
            try
            {
                Desktop.getDesktop().open(new File(selectedPath));
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error opening file: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_viewEvidenceButtonActionPerformed

    private void suspectsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suspectsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suspectsFieldActionPerformed

    private void crimeTypeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crimeTypeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crimeTypeFieldActionPerformed

    private void locationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationFieldActionPerformed

    private void incidentTimeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incidentTimeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_incidentTimeFieldActionPerformed

    private void incidentDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incidentDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_incidentDateFieldActionPerformed

    private void closingDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closingDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_closingDateFieldActionPerformed

    private void caseStartedFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caseStartedFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caseStartedFieldActionPerformed

    private void assisstantOfficerIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assisstantOfficerIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assisstantOfficerIdFieldActionPerformed

    private void leadOfficerIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leadOfficerIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leadOfficerIdFieldActionPerformed

    private void firIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firIdFieldActionPerformed

    private void investigationIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_investigationIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_investigationIdFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    private void loadInvestigation() 
    {
        investigationIdField.setText(investigation.getInvestigationId());
        firIdField.setText(investigation.getFirId());
        leadOfficerIdField.setText(investigation.getOfficerId1() != null ? investigation.getOfficerId1() : "");
        assisstantOfficerIdField.setText(investigation.getOfficerId2() != null ? investigation.getOfficerId2() : "");
        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
        caseStartedField.setText(sdf.format(investigation.getCreationDate()));
        closingDateField.setText(sdf.format(investigation.getLastUpdated()));
        suspectsField.setText(investigation.getSuspects());
        witnessTextArea.setText(investigation.getWitnessStatements());
        otherDetailsTextArea.setText(investigation.getOtherDetails());
        caseResultField.setText(investigation.getCaseResult());
        finalCriminalField.setText(investigation.getFinalCriminal());
        statusComboBox.setModel(new DefaultComboBoxModel<>(new String[]{ "Active", "Completed"}));
        statusComboBox.setSelectedItem(investigation.getStatus());
        CSVHandler.FIRData firData = csvHandler.getFIRData(investigation.getFirId());
        if (firData != null) 
        {
            complainantNameField.setText(firData.getComplainantName());
            complainantFatherNameField.setText(firData.getFathersName());
            contactField.setText(firData.getContact());
            addressField.setText(firData.getAddress());
            nicNoField.setText(firData.getNicNumber());
            incidentDateField.setText(firData.getIncidentDate() != null ? sdf.format(firData.getIncidentDate()) : "");
            incidentTimeField.setText(firData.getIncidentTime());
            locationField.setText(firData.getLocation());
            descriptionTextArea.setText(firData.getDescription());
            crimeTypeField.setText(firData.getCrimeType());
        }
    }
    
    public void disablecombo()
    {
        String officerId = csvHandler.getOfficerIdFromUsername(loggedInUsername);
        if (officerId != null && investigation.getOfficerId2() != null && investigation.getOfficerId2().equals(officerId) && (investigation.getOfficerId1() == null || !investigation.getOfficerId1().equals(officerId))) {
            statusComboBox.setEnabled(false);
        }
    }
    
    private void addEvidence() 
    {
        JFileChooser fileChooser = new JFileChooser();
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
        {
            String evidencePath = fileChooser.getSelectedFile().getAbsolutePath();
            evidencePaths.add(evidencePath);
            JOptionPane.showMessageDialog(this, "Selected: " + evidencePath);
        }
    }

    private void deleteEvidence()
    {
        if (evidencePaths.isEmpty()) 
        {
            JOptionPane.showMessageDialog(this, "No evidence to delete.", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        JList<String> evidenceList = new JList<>(evidencePaths.toArray(new String[0]));
        evidenceList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        JOptionPane.showMessageDialog(this, new JScrollPane(evidenceList), "Select Evidence to Delete", JOptionPane.PLAIN_MESSAGE);
        String selectedPath = evidenceList.getSelectedValue();
        if (selectedPath != null)
        {
            evidencePaths.remove(selectedPath);
        }
    }


    private void saveChanges()
    {
        String selectedStatus = (String) statusComboBox.getSelectedItem();
        String officerId = csvHandler.getOfficerIdFromUsername(loggedInUsername);
        
        if ("Completed".equals(selectedStatus) && (officerId == null || !officerId.equals(investigation.getOfficerId1()))) {
            JOptionPane.showMessageDialog(this, "Only the lead officer can set the status to 'Completed'.", "Permission Denied", JOptionPane.ERROR_MESSAGE);
            return;
        }

        investigation.setEvidencePaths(evidencePaths);
        investigation.setWitnessStatements(witnessTextArea.getText());
        investigation.setOtherDetails(otherDetailsTextArea.getText());
        investigation.setSuspects(suspectsField.getText());
        investigation.setCaseResult(caseResultField.getText());
        investigation.setFinalCriminal(finalCriminalField.getText());
        if (officerId != null && statusComboBox.isEnabled()) {
            investigation.setStatus(selectedStatus);
        }
        Date currentDate = new Date();
        investigation.setLastUpdated(currentDate);
        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
        closingDateField.setText(sdf.format(currentDate));
        csvHandler.addInvestigationDetails(investigation);
        JOptionPane.showMessageDialog(this, "Changes saved successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
        changesMade = false; 
        new OngoingCasesForm(loggedInUsername).setVisible(true);
        dispose();
    }
    
    
    
    
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvestigationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvestigationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvestigationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvestigationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvestigationForm(investigation, loggedInUsername).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JButton Savebtn;
    private javax.swing.JButton Savebtn1;
    private javax.swing.JButton addEvidenceButton;
    private javax.swing.JTextField addressField;
    private javax.swing.JTextField assisstantOfficerIdField;
    private javax.swing.JTextField caseResultField;
    private javax.swing.JTextField caseStartedField;
    private javax.swing.JTextField closingDateField;
    private javax.swing.JTextField complainantFatherNameField;
    private javax.swing.JTextField complainantNameField;
    private javax.swing.JTextField contactField;
    private javax.swing.JTextField crimeTypeField;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JTextField finalCriminalField;
    private javax.swing.JTextField firIdField;
    private javax.swing.JLabel headinglbl;
    private javax.swing.JTextField incidentDateField;
    private javax.swing.JTextField incidentTimeField;
    private javax.swing.JTextField investigationIdField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField leadOfficerIdField;
    private javax.swing.JTextField locationField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField nicNoField;
    private javax.swing.JTextArea otherDetailsTextArea;
    private javax.swing.JButton removeEvidenceButton;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JTextField suspectsField;
    private javax.swing.JButton viewEvidenceButton;
    private javax.swing.JTextArea witnessTextArea;
    // End of variables declaration//GEN-END:variables
}
