/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package police.gui;
import java.io.File;
import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.io.IOException;
import police.*;
/**
 *
 * @author HP
 */
public class PoliceDashboardForm extends javax.swing.JFrame {

    /**
     * Creates new form PoliceDashboardForm
     */
    private static String loggedInUsername;

    public PoliceDashboardForm(String loggedInUsername) 
    {
        this.loggedInUsername = loggedInUsername;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ProfileBtn = new javax.swing.JButton();
        FIRBtn = new javax.swing.JButton();
        CASEBtn = new javax.swing.JButton();
        CRIMINALBtn = new javax.swing.JButton();
        ANALYTICSBtn = new javax.swing.JButton();
        LOGOUTBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        VideoBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        FAQsOfficerBtn = new javax.swing.JButton();
        GuideBookbtn = new javax.swing.JButton();

        jButton5.setText("CRIMINAL DATABASE");
        jButton5.setMaximumSize(new java.awt.Dimension(74, 23));
        jButton5.setMinimumSize(new java.awt.Dimension(74, 23));
        jButton5.setPreferredSize(new java.awt.Dimension(74, 23));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Police Dashboard");
        setPreferredSize(new java.awt.Dimension(890, 670));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProfileBtn.setBackground(new java.awt.Color(0, 0, 0));
        ProfileBtn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        ProfileBtn.setForeground(new java.awt.Color(255, 255, 255));
        ProfileBtn.setText("PROFILE");
        ProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileBtnActionPerformed(evt);
            }
        });
        jPanel2.add(ProfileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 25, 170, 41));

        FIRBtn.setBackground(new java.awt.Color(0, 0, 0));
        FIRBtn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        FIRBtn.setForeground(new java.awt.Color(255, 255, 255));
        FIRBtn.setText("FIR MANAGEMENT");
        FIRBtn.setMaximumSize(new java.awt.Dimension(74, 23));
        FIRBtn.setMinimumSize(new java.awt.Dimension(74, 23));
        FIRBtn.setPreferredSize(new java.awt.Dimension(74, 23));
        FIRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIRBtnActionPerformed(evt);
            }
        });
        jPanel2.add(FIRBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 96, 170, 46));

        CASEBtn.setBackground(new java.awt.Color(0, 0, 0));
        CASEBtn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        CASEBtn.setForeground(new java.awt.Color(255, 255, 255));
        CASEBtn.setText("CASE MANAGEMENT");
        CASEBtn.setMaximumSize(new java.awt.Dimension(74, 23));
        CASEBtn.setMinimumSize(new java.awt.Dimension(74, 23));
        CASEBtn.setPreferredSize(new java.awt.Dimension(74, 23));
        CASEBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CASEBtnActionPerformed(evt);
            }
        });
        jPanel2.add(CASEBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 173, 170, 46));

        CRIMINALBtn.setBackground(new java.awt.Color(0, 0, 0));
        CRIMINALBtn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        CRIMINALBtn.setForeground(new java.awt.Color(255, 255, 255));
        CRIMINALBtn.setText("CRIMINAL DATABASE");
        CRIMINALBtn.setMaximumSize(new java.awt.Dimension(74, 23));
        CRIMINALBtn.setMinimumSize(new java.awt.Dimension(74, 23));
        CRIMINALBtn.setPreferredSize(new java.awt.Dimension(74, 23));
        CRIMINALBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CRIMINALBtnActionPerformed(evt);
            }
        });
        jPanel2.add(CRIMINALBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 254, 170, 46));

        ANALYTICSBtn.setText("ANALYTICS & REPORTS");
        ANALYTICSBtn.setBackground(new java.awt.Color(0, 0, 0));
        ANALYTICSBtn.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        ANALYTICSBtn.setForeground(new java.awt.Color(255, 255, 255));
        ANALYTICSBtn.setMaximumSize(new java.awt.Dimension(74, 23));
        ANALYTICSBtn.setMinimumSize(new java.awt.Dimension(74, 23));
        ANALYTICSBtn.setPreferredSize(new java.awt.Dimension(74, 23));
        ANALYTICSBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANALYTICSBtnActionPerformed(evt);
            }
        });
        jPanel2.add(ANALYTICSBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 338, 170, 46));

        LOGOUTBtn.setBackground(new java.awt.Color(204, 0, 0));
        LOGOUTBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LOGOUTBtn.setForeground(new java.awt.Color(255, 255, 255));
        LOGOUTBtn.setText("LOGOUT");
        LOGOUTBtn.setMaximumSize(new java.awt.Dimension(74, 23));
        LOGOUTBtn.setMinimumSize(new java.awt.Dimension(74, 23));
        LOGOUTBtn.setPreferredSize(new java.awt.Dimension(74, 23));
        LOGOUTBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTBtnActionPerformed(evt);
            }
        });
        jPanel2.add(LOGOUTBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 415, 170, 46));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 118, 180, 480));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Officer Support");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 130, 40));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Wide Latin", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("POLICE DASHBOARD");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 510, 60));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 860, 120));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Welcome, Officer! ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 480, 50));

        jScrollPane2.setBorder(null);

        jTextArea2.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("\"The first duty of a government is to maintain law and order, so that the life, property and religious beliefs of its subjects are fully protected by the state.\"\n\n-Quaid-e-Azam Muhammad Ali Jinnah");
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setBorder(null);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 500, 80));

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea3.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea3.setColumns(20);
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText("This principle guides us, not just as a duty, but as a sacred trust.");
        jTextArea3.setWrapStyleWord(true);
        jTextArea3.setBorder(null);
        jScrollPane3.setViewportView(jTextArea3);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 370, 30));

        jScrollPane4.setBorder(null);

        jTextArea4.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea4.setColumns(20);
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jTextArea4.setText("Our mission is simple yet profound:\n\n- To uphold justice without bias\n- To ensure equality before the law\n- To serve the community with honor, integrity, and compassion\n\nStay proud. Stay just. Serve with heart.\nPakistan Zindabad");
        jTextArea4.setWrapStyleWord(true);
        jTextArea4.setBorder(null);
        jScrollPane4.setViewportView(jTextArea4);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 360, 140));

        jScrollPane5.setBorder(null);

        jTextArea5.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea5.setColumns(20);
        jTextArea5.setLineWrap(true);
        jTextArea5.setRows(5);
        jTextArea5.setText("Welcome to duty, Officer.\n\nYou are more than just a guardian of the law - you are the strength behind justice, the shield for the innocent, and the voice for those who cannot speak. Every uniformed day is an opportunity to protect, to serve, and to lead by example. Your discipline, courage, and commitment echo the values our nation was built upon.");
        jTextArea5.setWrapStyleWord(true);
        jTextArea5.setBorder(null);
        jScrollPane5.setViewportView(jTextArea5);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 600, 100));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Our Mission :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 130, 50));

        VideoBtn.setBackground(new java.awt.Color(102, 204, 0));
        VideoBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        VideoBtn.setForeground(new java.awt.Color(255, 255, 255));
        VideoBtn.setText("Video Tutorial");
        VideoBtn.setBorderPainted(false);
        VideoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VideoBtnActionPerformed(evt);
            }
        });
        jPanel1.add(VideoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, 160, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Frequently Asked Questions");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 520, 160, 40));

        FAQsOfficerBtn.setBackground(new java.awt.Color(255, 255, 0));
        FAQsOfficerBtn.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        FAQsOfficerBtn.setText("FAQs");
        FAQsOfficerBtn.setBorderPainted(false);
        FAQsOfficerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FAQsOfficerBtnActionPerformed(evt);
            }
        });
        jPanel1.add(FAQsOfficerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, 80, 30));

        GuideBookbtn.setBackground(new java.awt.Color(153, 0, 0));
        GuideBookbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        GuideBookbtn.setForeground(new java.awt.Color(255, 255, 255));
        GuideBookbtn.setText("Officer GuideBook");
        GuideBookbtn.setBorderPainted(false);
        GuideBookbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuideBookbtnActionPerformed(evt);
            }
        });
        jPanel1.add(GuideBookbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 849, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CRIMINALBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CRIMINALBtnActionPerformed
        new CriminalForm(loggedInUsername).setVisible(true);
    }//GEN-LAST:event_CRIMINALBtnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void ANALYTICSBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANALYTICSBtnActionPerformed
       new AnalyticsDashboard().setVisible(true);

    }//GEN-LAST:event_ANALYTICSBtnActionPerformed

    private void LOGOUTBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTBtnActionPerformed
            Session.clearSession();
            new HomePageForm().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_LOGOUTBtnActionPerformed

    private void ProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileBtnActionPerformed
        new OfficerProfileForm(loggedInUsername).setVisible(true);
    }//GEN-LAST:event_ProfileBtnActionPerformed

    private void FIRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIRBtnActionPerformed
       new FIRForm(loggedInUsername).setVisible(true);
      
    }//GEN-LAST:event_FIRBtnActionPerformed

    private void CASEBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CASEBtnActionPerformed
       new CaseInvestigationDashboard(loggedInUsername).setVisible(true);

    }//GEN-LAST:event_CASEBtnActionPerformed

    private void VideoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VideoBtnActionPerformed
        String filePath = "./Resources/Other Stuff/Video Tutorial for Officers.mkv";
        try {
            File file = new File(filePath);
            if (file.exists())
            {
                Desktop.getDesktop().open(file);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "File not found: " + filePath, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (IOException e)
        {
            JOptionPane.showMessageDialog(this, "Failed to open file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        catch (UnsupportedOperationException e)
        {
            JOptionPane.showMessageDialog(this, "Opening files is not supported on this system.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_VideoBtnActionPerformed

    private void FAQsOfficerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FAQsOfficerBtnActionPerformed
       String filePath = "./Resources/Other Stuff/FAQsOfficers.pdf";
        try {
            File file = new File(filePath);
            if (file.exists())
            {
                Desktop.getDesktop().open(file);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "File not found: " + filePath, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (IOException e)
        {
            JOptionPane.showMessageDialog(this, "Failed to open file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        catch (UnsupportedOperationException e)
        {
            JOptionPane.showMessageDialog(this, "Opening files is not supported on this system.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_FAQsOfficerBtnActionPerformed

    private void GuideBookbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuideBookbtnActionPerformed
        String filePath = "./Resources/Other Stuff/OfficerGuideBookPMS.pdf";
        try {
            File file = new File(filePath);
            if (file.exists())
            {
                Desktop.getDesktop().open(file);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "File not found: " + filePath, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (IOException e)
        {
            JOptionPane.showMessageDialog(this, "Failed to open file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        catch (UnsupportedOperationException e)
        {
            JOptionPane.showMessageDialog(this, "Opening files is not supported on this system.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_GuideBookbtnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
            Session.clearSession();
            new PoliceLoginForm().setVisible(true);
            this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PoliceDashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PoliceDashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PoliceDashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PoliceDashboardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PoliceDashboardForm(loggedInUsername).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ANALYTICSBtn;
    private javax.swing.JButton CASEBtn;
    private javax.swing.JButton CRIMINALBtn;
    private javax.swing.JButton FAQsOfficerBtn;
    private javax.swing.JButton FIRBtn;
    private javax.swing.JButton GuideBookbtn;
    private javax.swing.JButton LOGOUTBtn;
    private javax.swing.JButton ProfileBtn;
    private javax.swing.JButton VideoBtn;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    // End of variables declaration//GEN-END:variables
}
